### ISSUE TITLE
Trex not installing dependencies from import_map.json

### ISSUE THREAD

**Issue by sant123** [crewdevio/Trex#100]
**Describe the bug**
After running `trex install` it does not cache the following dependencies:

``` json
{
  "imports": {
    "./": "./",
    "/": "./",
    "dayjs": "https://cdn.skypack.dev/dayjs@1.10.5?dts",
    "dayjs/plugin/": "https://cdn.skypack.dev/dayjs@1.10.5/plugin/",
    "flags/": "https://deno.land/std@0.93.0/flags/",
    "fs/": "https://deno.land/std@0.95.0/fs/",
    "neverthrow": "https://cdn.skypack.dev/neverthrow@4.2.1?dts",
    "path/": "https://deno.land/std@0.93.0/path/"
  }
}
```

**To Reproduce**
1. Execute `trex install > info.txt` with an import_map.json following the structure above
2. See this message in the first line of the file `"import_map.json file not found"`

**Expected behavior**
Should download and cache the dependencies from the import_map.json file

**Screenshots**
![image](https://user-images.githubusercontent.com/7959437/124503537-6a630900-dd8b-11eb-953d-8428e7487049.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 with KDE

Thank you!

**Comment by buttercubz** [comment]
I could already reproduce the bug, I will be working in the next few days to solve it

**Comment by sant123** [comment]
Thank you so much!!! I appreciate it

**Comment by buttercubz** [comment]
@sant123 please confirm if this issue not happen in dev branch

`to try dev branch`
```console
deno install -A -f -r -n trex --import-map=https://raw.githubusercontent.com/crewdevio/Trex/dev/import_map.json --no-check https://raw.githubusercontent.com/crewdevio/Trex/dev/cli.ts
```

**Comment by sant123** [comment]
Hey @buttercubz, I just tried the command above but didn't work. I also deleted the `trex_storage` and deno cache folder :/ but still shows the same message :/

**Comment by buttercubz** [comment]
> Hey @buttercubz, I just tried the command above but didn't work. I also deleted the `trex_storage` and deno cache folder :/ but still shows the same message :/

I am trying to reproduce using the dev branch but it seems to be fixed, please try to remove the deno cache folder and install the version of the dev branch

**Comment by sant123** [comment]
All right I just deleted the deno cache, trex folder and trex executable 

![image](https://user-images.githubusercontent.com/7959437/126017773-9f0be791-2bad-4e0d-a09e-8094d5c9227d.png)

And copy pasting this script

``` bash
deno install -A -f -r -n trex --import-map=https://raw.githubusercontent.com/crewdevio/Trex/dev/import_map.json --no-check https://raw.githubusercontent.com/crewdevio/Trex/dev/cli.ts
```


https://user-images.githubusercontent.com/7959437/126017999-96a6813a-e48a-4517-9c4c-9e192fb9d24f.mp4


https://user-images.githubusercontent.com/7959437/126018001-29908773-ccbd-4636-b2d5-7e7e9d7de5e3.mp4

Without success :/

This is how it looks now after the script above

![image](https://user-images.githubusercontent.com/7959437/126018055-e1d9a710-152e-4839-bbb9-fe22f612c101.png)

**Comment by buttercubz** [comment]
> All right I just deleted the deno cache, trex folder and trex executable
> 
> ![image](https://user-images.githubusercontent.com/7959437/126017773-9f0be791-2bad-4e0d-a09e-8094d5c9227d.png)
> 
> And copy pasting this script
> 
> ```shell
> deno install -A -f -r -n trex --import-map=https://raw.githubusercontent.com/crewdevio/Trex/dev/import_map.json --no-check https://raw.githubusercontent.com/crewdevio/Trex/dev/cli.ts
> ```
> 
>  1.mp4 
>  2.mp4 
> Without success :/
> 
> This is how it looks now after the script above
> 
> ![image](https://user-images.githubusercontent.com/7959437/126018055-e1d9a710-152e-4839-bbb9-fe22f612c101.png)

I already tried in macos and in ubuntu 20.04 and I have not been able to reproduce it

**Comment by sant123** [comment]
I just tried in a MacOS BigSur machine but I'm getting the same status:

![image](https://user-images.githubusercontent.com/7959437/126538610-d94fd0b8-91f1-445f-9455-9be7a0263cf1.png)

I get this when I do bash redirection:

![image](https://user-images.githubusercontent.com/7959437/126538725-796e2b65-c9a5-4ec1-8227-c61e335f3de2.png)

**Comment by sant123** [comment]
> @sant123 please confirm if this issue not happen in dev branch
> 
> `to try dev branch`
> 
> ```
> deno install -A -f -r -n trex --import-map=https://raw.githubusercontent.com/crewdevio/Trex/dev/import_map.json --no-check https://raw.githubusercontent.com/crewdevio/Trex/dev/cli.ts
> ```

Now it's working !! We forgot to include the --unstable flag. 

The ["import_map.json file not found"](https://github.com/crewdevio/Trex/blob/dev/handlers/handle_packages.ts#L199) is being caused by this:

TypeError: Deno.consoleSize is not a function
    at Spinner.updateLines (https://deno.land/x/wait@0.1.11/mod.ts:208:26)
    at Spinner.set text (https://deno.land/x/wait@0.1.11/mod.ts:135:10)
    at new Spinner (https://deno.land/x/wait@0.1.11/mod.ts:85:14)
    at wait (https://deno.land/x/wait@0.1.11/mod.ts:50:10)
    at LoadingSpinner (file:///Users/santiago.aguilar/Desktop/projects/Trex/tools/logs.ts:122:15)
    at cacheNestpackage (file:///Users/santiago.aguilar/Desktop/projects/Trex/handlers/handle_third_party_package.ts:66:19)
    at installPackages (file:///Users/santiago.aguilar/Desktop/projects/Trex/handlers/handle_packages.ts:180:21)
    at async Main (file:///Users/santiago.aguilar/Desktop/projects/Trex/cli.ts:72:25)
    at async file:///Users/santiago.aguilar/Desktop/projects/Trex/cli.ts:286:24

**Comment by sant123** [comment]
Both tested on MacOS BigSur and Fedora 33 :)

**Comment by buttercubz** [comment]
this is already fixed
