### ISSUE TITLE
Trex not found path

### ISSUE THREAD

**Issue by Rapougnac** [crewdevio/Trex#101]
**Describe the bug**

I tried to install trex with the command in the README.
The command worked perfectly and the message is `✅ Successfully installed trex`.
I tried to run `trex` and I get this error (in the screenshot)

**To Reproduce**
1. Install trex.
2. Run trex.
3. See error.

**Expected behavior**

Trex is supposed to show me the help pannel.

**Screenshots**
![Trex-err](https://user-images.githubusercontent.com/74512338/125485938-fe6585df-a2c3-4ac4-aebd-93ee97a8b769.PNG)
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser FireFox
 - Version 1909

**Comment by RivierGrullon** [comment]
what's your deno version?

**Comment by RivierGrullon** [comment]
Can you try it in another path route opening the powershell as administrator?

**Comment by Rapougnac** [comment]
> what's your deno version?
Deno is on the deno 1.12.0+1ad6575 (canary, x86_64-pc-windows-msvc) version.

> Can you try it in another path route opening the powershell as administrator?
I tried but I still got the same error, even with a different path.

**Comment by buttercubz** [comment]
> > what's your deno version?
> 
> Deno is on the deno 1.12.0+1ad6575 (canary, x86_64-pc-windows-msvc) version.
> 
> > Can you try it in another path route opening the powershell as administrator?
> 
> I tried but I still got the same error, even with a different path.

i trying to reproduce this but i can't, so you can create a `trex_storage` forlder in `.deno` folder and try again?

**Comment by Rapougnac** [comment]
> i trying to reproduce this but i can't, so you can create a trex_storage forlder in .deno folder and try again?

I tried but without sucess, I'm still getting the error

**Comment by kev2718** [comment]
For those who have the same problem. Add deno to your Path via (Powershell)
```$env:Path += ";C:\Users\<UserName>\.deno\bin"```

**Comment by Rapougnac** [comment]
Hi, I really apologize for the late reply, but I'm on vacation, I'll try this when I will be back to my home.

**Comment by Rapougnac** [comment]
I'm sorry for the reply, but I'm very busy. So I tried and it worked ! Thanks a lot. I thought deno was added to the path
