### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Lnncoco** [crewdevio/Trex#102]
**Describe the bug**
`trex run test.ts` , when my program throws an error , Trex will throw another error in the meantime  ` Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined `

**To Reproduce**

test.ts :
```
throw Error("error");
```

run.json
```
{
  "scripts": {
    "err": "deno run test.ts"
  }
}
```

executive command:
`trex run err`

trex throw another error infomation `error: Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined`

```
Check file:///D:/Project/deno-test/test.ts
error: Uncaught Error: error
throw Error("error");
      ^
    at file:///D:/Project/deno-test/test.ts:1:7
error: Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    ? `${code.open}${str.replace(code.regexp, code.open)}${code.close}`
                         ^
    at run (https://deno.land/std@0.99.0/fmt/colors.ts:69:26)
    at Module.yellow (https://deno.land/std@0.99.0/fmt/colors.ts:166:10)
    at Thread (https://deno.land/x/trex@v1.8.0/commands/run.ts:149:24)
    at async Run (https://deno.land/x/trex@v1.8.0/commands/run.ts:211:11)
    at async Main (https://deno.land/x/trex@v1.8.0/cli.ts:191:6)
    at async https://deno.land/x/trex@v1.8.0/cli.ts:286:24
```

run `deno run test.ts` only one error

**Expected behavior**

i hope it will be the same result like running command as `deno run test.ts`

**Comment by buttercubz** [comment]
i can't reproduce with the latest version of trex and deno:

https://user-images.githubusercontent.com/47539192/129248098-cff0f981-aed2-487a-b991-298117af19c2.mp4

you could specify the version of deno, trex and the operating system

**Comment by Lnncoco** [comment]
![test](https://i.loli.net/2021/08/13/zrIfaUZSBRXhdtl.gif)

trex: v1.8.0
Deno: v1.12.2
win 10 LTSC 1809   system locale  zh-cn
