### ISSUE TITLE
Not available in VSCode's terminal

### ISSUE THREAD

**Issue by kecrily** [crewdevio/Trex#103]
**Describe the bug**
Not available in VSCode's terminal, but everything is fine in Windows Terminal.

**To Reproduce**
1. Open VSCode and go to Terminal
2. Enter any of the commands under trex

```
error: Uncaught (in promise) TypeError: Path must be a string. Received undefined
    throw new TypeError(
          ^
    at assertPath (https://deno.land/std@0.99.0/path/_util.ts:18:11)
    at join (https://deno.land/std@0.99.0/path/win32.ts:333:5)
    at JsonStorage (https://deno.land/x/trex@v1.8.0/utils/storage.ts:41:9)
    at https://deno.land/x/trex@v1.8.0/handlers/handler_storage.ts:11:21
```

**Expected behavior**
Everything is fine, no errors are thrown

**Screenshots**

![bug](https://user-images.githubusercontent.com/45708948/130608285-7d9fad5c-ad87-4866-a0df-edec04acb89b.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Trex: 1.8.0
 - Deno: 1.12.2
 - VSCode: 1.59.1

**Additional context**

**Comment by kecrily** [comment]
I don't know what happened, but all of a sudden it turned back to normal

**Comment by buttercubz** [comment]
> I don't know what happened, but all of a sudden it turned back to normal

LMAO

**Comment by RivierGrullon** [comment]
> I don't know what happened, but all of a sudden it turned back to normal

LOL
