### ISSUE TITLE
Deno fails to install Trex v1.9.0

### ISSUE THREAD

**Issue by Druue** [crewdevio/Trex#105]
Running (Copy pasted from the v1.9.0 README) on a fresh repo:
```
deno install -A --unstable --import-map=https://deno.land/x/trex/import_map.json -n trex --no-check https://deno.land/x/trex/cli.ts
```

With the latest update to v1.9.0, trex now imports:
```
"wait": "http://denopkg.com/crewdevio/tools@main/wait/mod.ts"
```

Due to being a HTTP url, deno refuses to install Trex.
```
error: Modules imported via https are not allowed to import http modules.
  Importing: http://denopkg.com/crewdevio/tools@main/wait/mod.ts
    at https://deno.land/x/trex@v1.9.0/cli.ts:33:0
```

**Comment by buttercubz** [comment]
i can reproduce this error, i working to fix this asap

**Comment by buttercubz** [comment]
@Druue can you try again?

**Comment by Druue** [comment]
@buttercubz Works now! Had to manually specify @v1.9.1, think it still needs time to update as it seemed to default to 1.9.0 still when not adding a version.
