### ISSUE TITLE
Feature request – Allow specifying a custom output file name for the import map (e.g. import-map.json)

### ISSUE THREAD

**Issue by saadq** [crewdevio/Trex#112]
**Is your feature request related to a problem? Please describe.**

When I first started out with Deno I had always named the import map `import-map.json`. The `deno` CLI allows us to pass a `--import-map=` flag to specify our import map, and it doesn't seem like they default to `import_map.json` so it would be nice if Trex also allowed this to be configurable.

---

**Describe the solution you'd like**

I think it would be nice if we could have a flag to specify the output path like `-o ./import-map.json` or `-o imports.json` etc

---

**Describe alternatives you've considered**

N/A

---

**Additional context**

N/A

**Comment by buttercubz** [comment]
@saadq see https://github.com/crewdevio/Trex/tree/dev#local-configuration-and-global-configuration-experimental

**Comment by buttercubz** [comment]
> @saadq see https://github.com/crewdevio/Trex/tree/dev#local-configuration-and-global-configuration-experimental

@saadq if you want to try it before release, use:

```console
 trex upgrade --canary
```

**Comment by buttercubz** [comment]
@saadq done https://github.com/crewdevio/Trex#local-configuration-and-global-configuration-experimental
