### ISSUE TITLE
trex check incorrect latest version

### ISSUE THREAD

**Issue by beckend** [crewdevio/Trex#121]
`import_map.json`
```json
{
  "imports": {
    "fs/": "https://deno.land/std@0.125.0/fs/"
  }
}

```
```shell
❯ trex check
this is a deno.land/std package:

The package "fs" is outdate: current = 0.125.0; latest = 0.123.0;

[quick fix]: trex i -m fs@0.123.0

```

**To Reproduce** Steps to reproduce the behavior:

1. Use the import map file as above.
2. execute `trex check`

**Expected behavior** 
Not suggest an update command

**System:**

- OS: Arch Linux 5.16.8
- Deno version: 1.18.2
- Trex Version 1.10.0

**Comment by RivierGrullon** [comment]
Hi, Sorry for the late responde but I'm going to check the issue by myself if I can reproduce it

**Comment by buttercubz** [comment]
I was checking and the problem is that the latest version published under a tag is version 0.23.0, we use the tags releases to detect the latest version

https://github.com/denoland/deno_std/releases/tag/0.123.0

**Comment by beckend** [comment]
Perhaps it would be wise to point unto the tag path itself rather, since the nature of deno is path based mostly in URIs.

**Comment by buttercubz** [comment]
> Perhaps it would be wise to point to the tag path itself rather, since the nature of deno is path based mostly in URIs.

yes, it seems like a good idea

**Comment by buttercubz** [comment]
@beckend this bug has already fixed
