### ISSUE TITLE
all trex commands ruins

### ISSUE THREAD

**Issue by Gohryt** [crewdevio/Trex#122]
All deno commands ruins with:

`error: Uncaught (in promise) NotFound: No such file or directory (os error 2), mkdir '/home/gohryt/.deno/trex_storage/'
  if (!(await exists(storagePath))) await mkdir(storagePath);
                                    ^
    at async mkdir (deno:runtime/js/30_fs.js:109:5)
    at async JsonStorage (https://deno.land/x/trex@v1.10.0/utils/storage.ts:44:37)
    at async https://deno.land/x/trex@v1.10.0/handlers/handler_storage.ts:11:15

- OS: Fedora 35
- Deno version: 1.19
- Trex version: latest

**Comment by YukiDotN** [comment]
No idea why this happened, i've just test installing a dependency and it's ok. (On Deno v1.19.1)
