### ISSUE TITLE
Provide a Unique Selling Proposition for trex comparing it with Deno's new task runner

### ISSUE THREAD

**Issue by michael-spengler** [crewdevio/Trex#125]
since deno 1.20 introduced an integrated task runner (https://deno.com/blog/v1.20#new-subcommand-deno-task), it seems interesting to point out the benefits of using trex instead of deno task... 

I'm not that much into the details of trex & deno task yet - so I could not directly point this out in the readme via pull request or so. 

As an example use case it might be worth comparing how https://deno.land/x/snel would look like with deno task instead of using trex.

**Comment by ghaerdi** [comment]
Trex's script runner provides an installation lifecycle to run commands automatically before or after an installation with `preinstall` and `postinstall`.
After a long time we decided that we will remove the script runner for Trex v2. We will stay with the installation lifecycle unless Deno implements an alternative to npm's pre & post scripts.
Expect to see the `run` subcommand marked as deprecated in next versions and removed in Trex v2.
