### ISSUE TITLE
Merge run.json into import_map.json

### ISSUE THREAD

**Issue by Moroshima** [crewdevio/Trex#126]
This will make trex much more similar to the npm.

Or this may cause problem due to the deno plugin's config?

**Comment by buttercubz** [comment]
@Moroshima currently does not allow to use an import map that does not comply with the specification. see https://wicg.github.io/import-maps/

**Comment by buttercubz** [comment]
On the other hand, I do not want to modify the implemented standard, currently one of the strongest currents around deno is that web standards are respected

**Comment by Moroshima** [comment]
@buttercubz  Thanks, I understand.
