### ISSUE TITLE
Standard library and third-party modules have the same name

### ISSUE THREAD

**Issue by 8NAF** [crewdevio/Trex#128]
Hello,

I want to install the [`std/dotenv`](https://deno.land/std/dotenv) module, but there is a third party module with the same name ([`dotenv`](https://deno.land/x/dotenv)) and Trex always installs it instead of the standard library. How do I tell Trex that I want to install the standard library ?

**Comment by buttercubz** [comment]
yes i can reproduce this bug, for now you can install it using this command:

```console
trex --custom dotenv=https://deno.land/x/dotenv@v3.2.0/mod.ts
```

**Comment by 8NAF** [comment]
It has been almost a year, and now I am using `Trex` again, and everything seems to be working correctly. Therefore, I will close this issue.
