### ISSUE TITLE
Bad resource ID using the postinstall script

### ISSUE THREAD

**Issue by ghaerdi** [crewdevio/Trex#129]
**Describe the bug**

Throws a Bad resource ID after a package installation when the postinstall script is defined in the run file and the postinstall script doesn't run.

**To Reproduce**

1. Create a run.json file and define a postinstall script
2. Install a package

**Expected behavior** 

Should run the postinstall script after an installation without throwing errors.

**Screenshots**

```console
error: Uncaught (in promise) "Bad resource ID"
```

**Desktop (please complete the following information):**

- OS: ArcoLinux VM
- Deno version: v1.23.1
- Trex Version v1.11.0 current dev branch with this last commit [4c6fae0](https://github.com/crewdevio/Trex/commit/4c6fae03310b90745d2f325b042018883b9f45d8)

**Additional context**

The code works well until below this comment, in the line 133 throws the error: [4c6fae0](https://github.com/crewdevio/Trex/commit/4c6fae03310b90745d2f325b042018883b9f45d8)

**Comment by RivierGrullon** [comment]
81a5968dac52fbe010fbe39de3819a0d708ea531
