### ISSUE TITLE
NotFound: No such file or directory

### ISSUE THREAD

**Issue by Dragonizedpizza** [crewdevio/Trex#135]
**Describe the bug** A clear and concise description of what the bug is.

When running `trex install --map fs` with my own entries in import_map.json, an error is produced saying `NotFound: No such file or directory`.

**To Reproduce** Steps to reproduce the behavior:

`trex install --map fs` results in error saying
```
time to installation: 2.8s
error: Uncaught (in promise) "NotFound: No such file or directory (os error 2)"
```

After some more testing, I found out that its import_map - when I run it with an import_map which doesn't have my own entries within it, no such error is produced.

[import_map.json](https://hastebin.com/upudabesih.json)

**Expected behavior** A clear and concise description of what you expected to
happen.

To install without an error.

**Screenshots** If applicable, add screenshots to help explain your problem.

![TrexTest](https://user-images.githubusercontent.com/70718540/213619781-35f66fab-2ded-445c-8b75-93c479e54b26.gif)
(trex also consumes extra lines when running `trex install`)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Deno version: 1.29.2
- Trex Version: 
![image](https://user-images.githubusercontent.com/70718540/213618926-feefb3ae-e96b-4d28-8684-203383eaddb4.png)
some version bug? it says I upgraded to 1.12.0 when using trex upgrade --canary but trex --version outputs 1.11.0.

**Additional context** Add any other context about the problem here.

**Comment by Dragonizedpizza** [comment]
After some more testing, I found out this is due to the npm entries.

**Comment by RivierGrullon** [comment]
Hi, sorry for the late response we've been kind of busy and some features of trex got broken in some deno updates and we need to update and fix trex (actually the output of trex --version is because this file is out of date https://github.com/crewdevio/Trex/tree/master/utils )

**Comment by Dragonizedpizza** [comment]
oh, alright. when will there be a fix for this?

**Comment by RivierGrullon** [comment]
I'm going to keep an eye on it to see if I can do something, but any PR is also welcome, I'll take care of reviewing it and mixing it

**Comment by ghaerdi** [comment]
Trex was trying to read npm dependencies as a local file path to generate a hash and check the file integrity. For now we are not checking npm dependencies until #134. The fix is already released.
