### ISSUE TITLE
A command to cache all dependencies

### ISSUE THREAD

**Issue by Dragonizedpizza** [crewdevio/Trex#141]
**Is your feature request related to a problem? Please describe.**
Typings while coding in a new environment aren't provided due to the module not being installed, and there is no command to cache them.

**Describe the solution you'd like**
`trex cache` - caches (installs) http urls in import_map.json

**Describe alternatives you've considered**

**Additional context**

**Comment by ghaerdi** [comment]
Currently Deno has the same command.
What would be the main difference between `trex cache` and `deno cache`?
@Dragonizedpizza

**Comment by jeff-hykin** [comment]
I'm pretty sure this can be safely closed

**Comment by DragonZV** [comment]
> Currently Deno has the same command.
> What would be the main difference between `trex cache` and `deno cache`?
> @Dragonizedpizza

at the time I wasn't aware deno cache was a thing, sorry 💀

**Comment by jeff-hykin** [comment]
there's also `deno vendor` which I like cause it's easier to transfer to other machines
