### ISSUE TITLE
[FEATURE]: Set nest.land as package registry

### ISSUE THREAD

**Issue by tbaumer22** [crewdevio/Trex#24]
Hi! I've had my eye on Trex for quite awhile now, and I think it's a really cool project!

I'm an author of [nest.land](https://nest.land) - An immutable, blockchain powered package registry for Deno. I was wondering if you would be interested in adding Trex to our registry? I think the nest.land ecosystem would benefit greatly from this, and I also think that Trex would benefit because the Trex code would be permanently accessible from the web.

Here is a link to our documentation if you'd be interested in adding it: https://nest.land/docs

Let me know if you have any questions!

Tate

**Comment by buttercubz** [comment]
Of course, I just saw nest.land and I think it is a very promising project, can you provide us some communication method to show you a proposal that we have?

**Comment by tbaumer22** [comment]
@buttercubz you can reach me on Discord at tate#5885 if you’d like to discuss something!
