### ISSUE TITLE
use lowercase "t" and rename to "trex"

### ISSUE THREAD

**Issue by trivikr** [crewdevio/Trex#39]
**Is your feature request related to a problem? Please describe.**
Almost all commands run in terminal are all composed of small letters, Trex with uppercase "t" would be difficult to type

**Describe the solution you'd like**
Rename "Trex" to "trex"

**Describe alternatives you've considered**
Type uppercase "t" in Trex by pressing shift every time

**Comment by RivierGrullon** [comment]
We're working on that, soon we'll be release Trex 1.1.0.

In that version "Trex" command will pass to "trex". :)

**Comment by RivierGrullon** [comment]
buuut you can use this way to install Trex deno install -A --unstable -n trex Trex.ts.

and you will be get Trex into trex.

**Comment by trivikr** [comment]
> We're working on that, soon we'll be release Trex 1.1.0.

Did you mean 1.0.0?
The latest release is [v1.0.0-rc2](https://github.com/crewdevio/Trex/releases/tag/v1.0.0-rc2), I think this should be introduced before 1.0.0 goes stable.

**Comment by trivikr** [comment]
@buttercubz 

Should "good first issue" label be removed from this issue?
As per response from collaborator @RivierGrullon in https://github.com/crewdevio/Trex/issues/39#issuecomment-658531684, this is already being worked on.

**Comment by RivierGrullon** [comment]
@trivikr 
We made some changes to trex, and there was an error posting [Trex version](https://nest.land/package/Trex) in nest.land is 1.1.0 instead of 1.0.0... So I really apologize for that, checkout the Readme :)

**Comment by trivikr** [comment]
No worries, I'd thought `1.1.0` to be a mistake, so had replied to confirm.

How about renaming the repository too from "Trex" to "trex"?
Instructions: https://docs.github.com/en/github/administering-a-repository/renaming-a-repository
