### ISSUE TITLE
Release changes to egg.json

### ISSUE THREAD

**Issue by tranzystorek-io** [crewdevio/Trex#48]
Trex cannot be installed from nest.land until a new version is published there that includes the `cli.ts` file.

**Comment by buttercubz** [comment]
Yes, I just confirmed that the `mod.ts` file is still registered as the input file in `nest.land`, we are contacting the `nest.land` team to fix it

**Comment by tranzystorek-io** [comment]
My point is that the cli.ts file is not published to nest:
![obraz](https://user-images.githubusercontent.com/5671049/89132252-27613b80-d513-11ea-8797-1f7192ba366f.png)

**Comment by buttercubz** [comment]
I just saw the problem, it was in the egg.json file and it was fixed, we wait until the next update to upload the update since nest.land does not allow uploading without updating the version

**Comment by tranzystorek-io** [comment]
Maybe you could create version 1.1.3 with just this change, since it's an important fix?

**Comment by buttercubz** [comment]
@tranzystorek-io I think it would be the right thing

**Comment by tranzystorek-io** [comment]
Resolved, closing
