### ISSUE TITLE
Can't install deno std modules with a custom name

### ISSUE THREAD

**Issue by AZMCode** [crewdevio/Trex#58]
**Describe the bug**
Trex won't assign a correct mapping from std even if a name is supplied 

**To Reproduce**
`trex install --map fs=https://deno.land/std@0.66.0/fs`
Now the import_map.json has an entry as such:
`"": "https://deno.land/std@0.66.0/fs/mod.ts"`

**Expected behavior**
import_map.json contains an  `"fs": "https://deno.land/std@0.66.0/fs/mod.ts" `

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu
 - Deno
 - deno 1.3.0
 - v8 8.6.334
 - typescript 3.9.7

**Additional context**
Log when running above command:
```
cache package... 

package not found.
cache package... 

time to installation: 1.7s
Package list: 
    |-  
    |-  webview
Happy Coding
```

**Comment by buttercubz** [comment]
#60
