### ISSUE TITLE
Imports should never be used to import types error

### ISSUE THREAD

**Issue by shadowtime2000** [crewdevio/Trex#68]
**Describe the bug**
I tried to download the `trex@imports` version and Deno gave me a ton of errors regarding the importing of types. It says that it should import types with `import type` instead of `import`

**To Reproduce**
1. Run `deno install -A --unstable -n trex https://denopkg.com/crewdevio/Trex@imports/cli.ts`

**Expected behavior**
I expected it to download `trex`

**Screenshots**
![image](https://user-images.githubusercontent.com/66655515/95354648-80ce4980-0879-11eb-8d3a-1199c2ab2164.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Additional context**
This is probably an easy fix and I will try to do it myself.

**Comment by buttercubz** [comment]
@shadowtime2000 I have already fixed it please try again

**Comment by shadowtime2000** [comment]
@buttercubz Nope, same errors.

**Comment by buttercubz** [comment]
> @buttercubz Nope, same errors.

works for me, try `deno install -r -f -A --unstable -n imports https://denopkg.com/crewdevio/Trex@imports/cli.ts` then `imports --help`

**Comment by shadowtime2000** [comment]
👍 works now
