### ISSUE TITLE
[FEATURE REQUEST] run.yaml 

### ISSUE THREAD

**Issue by promethyttrium** [crewdevio/Trex#75]
In addition to having `run.json`, please support `run.yaml`. YAML is shorter and easier to write, but most of all, you can have comments. This is essentially a 1- or 2-line change inside `run.ts`.

Love the idea of TRex!!!

PS: completely unrelated, any  thoughts of naming the `imports` command as `trix` -- shorter command, `i` is for `import`, unfortunately, it's not dinosaur-themed.

**Comment by buttercubz** [comment]
thanks for the suggestion @promethyttrium, it seems like a good idea to add support to `yml`

**Comment by buttercubz** [comment]
@promethyttrium I just added the support for ` yaml`, we hope to release version v1.4.0 together with the new version of deno, but you can try it from the dev branch
