### ISSUE TITLE
'trex' not found

### ISSUE THREAD

**Issue by RilDev** [crewdevio/Trex#81]
**Describe the bug**
I ran the command in the install section of the documentation:
```
deno install -A --unstable -n trex --no-check https://deno.land/x/trex/cli.ts
```
But when I run `trex`, I get a message `'trex' not found, did you mean:...`
 
**To Reproduce**
1. Install Trex with `deno install -A --unstable -n trex --no-check https://deno.land/x/trex/cli.ts`
2. Close terminal
3. Reopen terminal and run `trex`

**Desktop:**
 - OS: Ubuntu 20, Windows 10

**Comment by buttercubz** [comment]
thanks for the report, i confirmed that problem, i try to fix it asap

**Comment by RilDev** [comment]
Good day,

The last PR didn't fix my problem. I updated Trex and reopened my terminal, but it still doesn't work.

![trex-not-found](https://user-images.githubusercontent.com/13135150/107330493-e9406800-6ab1-11eb-9927-5bf2669770b6.gif)

**Comment by RivierGrullon** [comment]
https://user-images.githubusercontent.com/45011060/107365423-2a854780-6ab3-11eb-92ee-f8c131f94a1a.mp4

We didn't make a new release but the bug was fixed, so when we make another release this will not happen meanwhile you can clone the repository and open the folder in your terminal and write 

```shell
deno install -A --unstable -n -f trex --no-check ./cli.ts
```

**Comment by RivierGrullon** [comment]
I didn't realize that you don't have the path for binaries for deno in your console, you need to add manually in linux

go to the .bashrc and write what appeared to you about exporting in the terminal 

export PATH="/home/{username}/.deno/bin:$PATH"

**Comment by RilDev** [comment]
Thanks, adding `~/.deno/bin` to my path fixed it! Sorry for the blunder.
For info, I installed Deno using `cargo install deno`.

`trex -h` returns:

```
advanced package management for deno, based on import_map.json

USAGE:
   trex [OPTIONS] [SUBCOMMAND]

OPTIONS:
   -h, --help      print help info
   -c, --custom    install custom package
   -v, --version   print version
   -m, --map       install package from deno.land
   -n, --nest      install package from nest.land
   -p, --pkg       install package from some repository

SUBCOMMANDS:
   [install or i]  install a package
   delete          delete a package
   upgrade         update trex
   tree            view dependency tree
   run             run a script alias in a file run.json
   setup           create a deno configuration for your IDE
   purge           remove a package or url from cache
   ls              shows the list of installed packages

you can see the different options available for each command using:
   trex  [command] --help or -h
```

But, I'm still having errors when I try to import modules through Trex.

Using these imports:

```
// scripts/plugin-name/main.ts
import {
  assert,
  assertEquals,
  assertThrowsAsync,
} from "testing/asserts.ts";
import { exists } from "fs/mod.ts";
...
```

`deno test -A --unstable scripts/` gives me this error:

```
Check file:///home/rildev/Projects/olivetan/$deno$test.ts
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'assert'.
  assert,
  ~~~~~~
    at file:///home/rildev/Projects/olivetan/scripts/modernize-transcript/tests/main.test.ts:2:3

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'assertEquals'.
  assertEquals,
  ~~~~~~~~~~~~
    at file:///home/rildev/Projects/olivetan/scripts/modernize-transcript/tests/main.test.ts:3:3

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'assertThrowsAsync'.
  assertThrowsAsync,
  ~~~~~~~~~~~~~~~~~
    at file:///home/rildev/Projects/olivetan/scripts/modernize-transcript/tests/main.test.ts:4:3

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'exists'.
import { exists } from "fs/mod.ts";
         ~~~~~~
    at file:///home/rildev/Projects/olivetan/scripts/modernize-transcript/tests/main.test.ts:6:10

Found 4 errors.
```

Here is my setup:

```
// .vscode/settings.json
{
    "deno.enable": true,
    "deno.import_map": "./import_map.json",
    "deno.unstable": true
}
```

```
// import_map.json
{
  "imports": {
    "fs/": "https://deno.land/std/fs/",
    "testing/": "https://deno.land/std/testing/"
  }
}

```

Steps Followed:
- Install dependencies with `trex i -m fs testing`
- Run `deno test -A --unstable scripts/` or `trex run test` aliasing the same command
- Run `trex install`
- Repeat

Is it a bug or I miss-configured something?

**Comment by buttercubz** [comment]
> Is it a bug or I miss-configured something?

try adding --import-map flag:

```console
deno test -A --unstable import-map=./import_map.json scripts/
```

**Comment by RilDev** [comment]
Thanks for you help!

I just noticed it after sending the message.
