### ISSUE TITLE
Pruning unused imports

### ISSUE THREAD

**Issue by turastory** [crewdevio/Trex#87]
**Is your feature request related to a problem? Please describe.**
User can clean up their import map by removing unused imports. I'm not sure if it's necessary since it's just an import map, but it would be quite useful for those who wants to figure out which packages are used, for example.

**Describe the solution you'd like**
Provide a way to optimize import map using a command like `trex prune`

**Additional context**
I'm wondering how many needs are there for this kind of functionality.
I am worried that the traversal may be way too complex and time-consuming task, compared to other commands.

By the way, thanks your effort in developing Trex 😃

**Comment by buttercubz** [comment]
Thanks for your suggestion, this command would be useful for some users but i think it would be very difficult to implement this command, also i think its use would be for few people
