### ISSUE TITLE
Running 'imports upgrade' gives syntax error

### ISSUE THREAD

**Issue by NexWasTaken** [crewdevio/Trex#88]
Running 'imports upgrade' gives syntax error.

Logs: 
```
λ imports upgrade
Check https://denopkg.com/crewdevio/Trex@imports/cli.ts
error: Uncaught (in promise) SyntaxError: Unexpected token I in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (deno:op_crates/fetch/26_fetch.js:843:19)
    at async updateTrex (https://raw.githubusercontent.com/crewdevio/Trex/imports/utils/logs.ts:28:24)
    at async mainCli (https://raw.githubusercontent.com/crewdevio/Trex/imports/cli.ts:119:5)
    at async https://raw.githubusercontent.com/crewdevio/Trex/imports/cli.ts:170:3
```

**Comment by buttercubz** [comment]
Thank you for your report, I will review it asap

**Comment by buttercubz** [comment]
see #92

**Comment by borsemayur2** [comment]
I'm getting following type errors on `trex upgrade` from `1.6` to `1.7`
![image](https://user-images.githubusercontent.com/47341981/119286172-5b078080-bc61-11eb-8e87-7c07407f7df2.png)

**Comment by buttercubz** [comment]
> I'm getting following type errors on `trex upgrade` from `1.6` to `1.7`
> ![image](https://user-images.githubusercontent.com/47341981/119286172-5b078080-bc61-11eb-8e87-7c07407f7df2.png)

please reinstall again this is a breaking change, now we use import maps

```console
deno install -f -A --unstable --import-map=https://deno.land/x/trex/import_map.json.ts -n trex --no-check https://deno.land/x/trex/cli.ts
```
