### ISSUE TITLE
The property `deno.import_map` is not recognized anymore on VS Code's Deno extesion. 

### ISSUE THREAD

**Issue by pedropalhari** [crewdevio/Trex#89]
**Describe the bug**
The property `import_map` on VS Code Deno extension is now `importMap`. Trex is creating it wrongly as of today.

**To Reproduce**
1. Execute `trex setup --vscode`
2. Check that it created `.vscode/settings.json` with `deno.import_map` property.

**Expected behavior**
The `deno.import_map` property should be `deno.importMap`.

**Desktop (please complete the following information):**
 - OS: Pop_OS! 20.10

**Comment by buttercubz** [comment]
thanks for your problem report, this functionality has been removed in the next version to be released soon #85 

use this instead https://github.com/denoland/vscode_deno#commands
