### ISSUE TITLE
does not install if absolute path mappings are specified in import_map.json

### ISSUE THREAD

**Issue by sramam** [crewdevio/Trex#98]
Starting with a import_map.json that has mappings for absolute paths
```
{
  "imports": {
    "/": "./",
    "./": "./",
  }
}
```

```
trex --custom react=https://esm.sh/react@17.0.1
```

results in an error:
```
error: Uncaught (in promise) PermissionDenied: Access is denied. (os error 5)
    const buffer = await Deno.readFile(path);
                ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async open (deno:runtime/js/40_files.js:46:17)
    at async Object.readFile (deno:runtime/js/40_read_file.js:20:18)
    at async readURLContent (https://deno.land/x/trex@v1.7.0/handlers/handle_files.ts:96:17)
    at async generateHash (https://deno.land/x/trex@v1.7.0/handlers/handle_files.ts:107:14)
    at async createPackage (https://deno.land/x/trex@v1.7.0/handlers/handle_files.ts:59:52)
```

Removing the absolute maps solves the problem.

**Comment by buttercubz** [comment]
i can confirm this bug

**Comment by buttercubz** [comment]
this problem is fixed in dev branch

**Comment by sramam** [comment]
verified! thanks for the quick turn around.

**Comment by sant123** [comment]
Tested with v1.8.0 but getting this error with the following dependencies:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/7959437/124323095-524e7800-db46-11eb-97a8-44a347ea907a.png">

Sorry is it something I'm doing wrong? Please let me know.

Thanks!

**Comment by buttercubz** [comment]
> Tested with v1.8.0 but getting this error with the following dependencies:
> 
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/7959437/124323095-524e7800-db46-11eb-97a8-44a347ea907a.png">
> 
> Sorry is it something I'm doing wrong? Please let me know.
> 
> Thanks!

hi, it seems that you are trying to verify the integrity of a path that is not a package "`/`", a quick solution would be to delete the trex_storage folder that is in the `.deno` folder and doing a trex install again

**Comment by sant123** [comment]
It works!!! Thank you so much!

**Comment by sant123** [comment]
I'll leave this script for someone who needs to test this feature meanwhile this [PR](https://github.com/crewdevio/Trex/pull/96) gets merged:

``` bash
deno install -Af --unstable --import-map=https://raw.githubusercontent.com/crewdevio/Trex/dev/import_map.json -n trex --no-check https://raw.githubusercontent.com/crewdevio/Trex/dev/cli.ts
```
